version: '2'
services:
   nginx:
      # 指定当前构建的Docker容器的镜像
      image: gsy36559067/nginx:0.1
      restart: always
      # 指定当前构建的Docker容器的名称
      container_name: nginx-0.1
      # 指定当前构建的Docker容器的volume挂在目录设置
      volumes:
         - /docker/docker/nginx/html:/usr/share/nginx/html 
         - /docker/docker/nginx/conf.d:/etc/nginx/conf.d
         - /docker/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
         - /docker/docker/nginx/log:/var/log/nginx
      # 指定当前构建的Docker容器对外开放的端口号映射
      ports:
         - "80:80"
